### ISSUE TITLE
recipes disappearing

### ISSUE THREAD

**Issue by Ozzymud** [TeamBR-Modding/AssistedProgression#10]
Forge 14.23.0.2550
AssistedProgression-1.12.2-2.0-B23

Not really sure where to look for an error here, but I put together a pack of uncommon mods. This one for a crafting table that keeps it's inventory. In game I made a dual crafter and made a stone axe in it. All was good. I was showing my son the mod and re-opened the table with said axe in my hand... it disappeared from my inventory and then I was no longer able to craft stone axes (even in a vanilla table). The recipe still shows up in JEI and jei will happily move the items into the left grid, but there is no output.  

I then tried to craft a wooden axe, success as expected. right clicked the dual crafter with it and it also disappeared and I was no longer able to craft wood axes. Cheated in some iron ingots(very early game :P) and was able to lose the ability to craft more of those as well.  

Upon full game reload the axes were back and I was unable to recreate at 1st. Then I shift clicked the resulting axe out of the table, right clicked the table with the axe, it disappeared and I was again unable to craft that type of axe. Shift clicking the result out of the table was the key. Same shift clicking with the vanilla bench does not cause the issue. Also when right clicking the dual crafter with the axe, if I have the right materials in inventory they are placed into the left grid, but there is no output.

![2017-11-21_23 28 03](https://user-images.githubusercontent.com/6426344/33114866-a67ad042-cf13-11e7-91e7-8183e598b275.png)

**Comment by Ozzymud** [comment]
As an update to the above, made a new instance with just this mod and was able to reproduce. this time with oak wood planks (which the 1st craft gave me 64 planks from one oak wood) that also disappeared...

![2017-11-21_23 35 53](https://user-images.githubusercontent.com/6426344/33115137-c38d735a-cf14-11e7-86d9-2d5ec4690800.png)

**Comment by pauljoda** [comment]
I did notice something about that. Its really weird, thanks for verifying it wasn't just me

**Comment by Ozzymud** [comment]
Will this also fix another issue, It's another wierd one to explain. I have silent's gems installed, and trying to craft one of the component items. Pressing U on the resource shows 2 uses, one is to make a block out of 9 shards, the other is an upgraded shard. Now clicking + to add one items worth of stuff into the grid shows the correct output, shift clicking the plus to craft as many possible will show the output as the block(9 shard craft like a block of iron)... removing any one component and just placing one in that spot corrects the output. This is in ANY crafting table and removing not the mod, but it's library ?nucleus? afterwards corrected that issue.

**Comment by pauljoda** [comment]
Yeah it should. If you want to test, the home page of this project has a link to the latest team city build. Click that widget in the read me and try that
