### ISSUE TITLE
Suggestion:

### ISSUE THREAD

**Issue by iobiarg** [TeamBR-Modding/AssistedProgression#15]
I love the grinder, and i think that's the only think I use. But since other mods ways to double ore are mid game expensive, maybe you could add a way to upgrade the grinder beyond the pressure plate used. like for instance a crank to make it work without jumping (it actually gives me headaches so y put sth over the space key and leave my steve jumping while i go do sth). Or maybe a way to turn to electric.

maybe you could think water colector (from rain?)  or a better fish trap (the one in pams harvestcraft is anoying af but is a nice option since is not techy ), and/or some sort of lamp with bigger range (or maybe some sort of bigger torch or like a fire pit... lets say like the decorative pot in Garde stuff mod with netherack as soil) (this mod doesnt work for me so i would like that item but to be more powerfull than a torch.

i hope u like any of this ideas... kisses from argentina

Sorry for my bad English.

**Comment by pauljoda** [comment]
I am closing this issue for now, we will consider the ideas listed and readd them to the development board as needed
