### ISSUE TITLE
[1.14.4] Crash on launch due to Tree Choppin

### ISSUE THREAD

**Issue by WenXin20** [TeamBR-Modding/AssistedProgression#18]
Forge v28.0.102
Minecraft v1.14.4
Assisted Progression v5.0-B26
Nucleus v 2.0

I get this crash on game launch. The first time loading the mod worked fine, but after that I got this crash.
[Crash Report](https://gist.github.com/WenXin20/299921edbc5c66ec41f23c86b9355893)

**Comment by WenXin20** [comment]
Ok, I think I know what went wrong.

I had incorrectly defined a log block for Tree Choppin config file, but instead of showing the normal dirt background that described what went wrong with the config file, this mod crashed instead.

Fixing the config entry for Tree Choppin stopped the crashing with this mod.

**Comment by WenXin20** [comment]
The mod Storage Drawers also had the same crash due to Tree Choppin.
If any more info is needed check here: jaquadro/StorageDrawers#737

**Comment by pauljoda** [comment]
Yeah I have no idea what that mod is doing but they are crashing the forge loader. They may need to update to a newer forge. Closing unless that mod can provide more info on what they’re doing, their code doesn’t seem to be open
