### ISSUE TITLE
Pipette Crash

### ISSUE THREAD

**Issue by WenXin20** [TeamBR-Modding/AssistedProgression#19]
Forge v28.1.1
Minecraft v1.14.4
Assisted Progression v5.0-B26
Nucleus v2.0
JEI v6.0.0.11

The pipette will crash Minecraft when trying to visit the creative tab, while JEI will simply prevent the Pipette from displaying at all.
[Crash Report](https://gist.github.com/WenXin20/06a70dae9981af9817d0e6d4b6fc626b)

**Comment by Dyonovan** [comment]
Looks like they changed a method name. Will look into this asap.

**Comment by Dyonovan** [comment]
There is a newer version out already that fixes this. Closing
