### ISSUE TITLE
Suggestion: Syringe

### ISSUE THREAD

**Issue by jburrows82** [TeamBR-Modding/AssistedProgression#2]
I don't remember which mod had it, I think it was Modular Systems... maybe Neotech? But the Syringe/Dropper for pulling out less than one bucket of fluid is a real quality of life tool for things like Tinkers' casting basins when you under pour alloys and have to break the table/basin. 

Another idea but with automation in mind (Tinkers' undercasting in mind):

A configurable fluid detector for purposes of detecting insufficient casting quantities and setting up an automated dump or recycle back into a Smeltery would be useful too. You guys have that fancy sided configuration GUI, so perhaps allow the block to output a redstone signal to a configurable side. Perhaps even allow multiple sided fluid inventories to be checked, and output a redstone signal if any sides are below the configured amount. Configurable delay in checking of fluid amounts. Perhaps a toggle option to not emit a redstone signal if fluid amount has increased since last check, even if it's still below configured amount.

**Comment by pauljoda** [comment]
This is actually something we are going to add. I added the syringe at some random point in the past. No idea where either but it was a thing. It will be in this mod as well. I'll keep in mind the second idea as well. Seems interesting.

If you want to keep up to date on what we have going on, head over to our trello. 
https://trello.com/b/ftNf75Pq/assisted-progression
