### ISSUE TITLE
Crash w/ generateDynamicRecipes

### ISSUE THREAD

**Issue by WenXin20** [TeamBR-Modding/AssistedProgression#20]
Minecraft v1.14.4
Forge v28.1.10
Nucleus v5.0
Assisted Progression v2.0

I got this crash after loading up a world. It was previously working fine, so I'm not sure what caused it.
[Crash Report](https://gist.github.com/WenXin20/69fd629d7731032524686b520cdcf286)

**Comment by Dyonovan** [comment]
Did you add any mods between the saves? Or change any configs?

**Comment by WenXin20** [comment]
I haven't changed any configs, but I did add a couple of mods. I added Steve's Factory Manager, Wyrmm Roost & Citadel, World Handler, Gift from the Gods, & Healing Campfire.

**Comment by pauljoda** [comment]
I think I can see what is causing the issue but would need a little more info. Those values should never be null unless another mod has caused the load to fail. Can you try removing a mod at a time to find which one is causing it to fail? That or if you can post the FMLlatest log I might be able to see

**Comment by LlubNek** [comment]
getting the same crash when generating a new world.

I'm using FTB Unstable 1.14 plus the following mods:
Mouse Tweaks
Ore Excavation
SwingThroughGrass
Clumps
BetterAdvancements
Hwyla
KleeSlabs
Quick Leaf Decay
DRP - Global Data Pack
Ring of Repair [FORGE]
Ring of the Miner [FORGE]
Ring of the Enderchest [FORGE]
Ring of Blink [FORGE]

[crash-2019-10-13_01.54.20-server.txt](https://github.com/TeamBR-Modding/AssistedProgression/files/3721469/crash-2019-10-13_01.54.20-server.txt)
[latest.zip](https://github.com/TeamBR-Modding/AssistedProgression/files/3721470/latest.zip)

**Comment by MelanX** [comment]
I have the same problem by creating a Unstable 1.14 server.
Here you can find my crash report: https://pastebin.com/D2EVC6Hs

**Comment by pauljoda** [comment]
Can you try loading with Simple Farming? Right before our crash they crash the tag builder which could very easily crash us as we assume mods are formatting the correct way. I may have to add Null checks, but then it would load but have no dynamic recipes. If removing simple farming prevents the crash we will look into it more

**Comment by WenXin20** [comment]
I would help too, but I've been unable to reproduce the crash, even though Simple Farming is installed.
