### ISSUE TITLE
Client crash when shift-click item with hefty bag open.

### ISSUE THREAD

**Issue by fuzzyweapon** [TeamBR-Modding/AssistedProgression#22]
Client crash when shift-click item with hefty bag open.

The client hung and I had to kill it with OS process manager.

----
Assisted Progression - 1.14.4-2.0
MC - 1.14.4
Forge - 1.14.4 - 28.1.10
JEI - 6.0.0.13

**Comment by fuzzyweapon** [comment]
The debug log is too big to use pastebin free, so I had to filter it to "assisted" and then added in the last **bit** of the debug.log where the error occurred.  Doesn't seem to shed any light on the matter, but this bug is 100% reproducibility, so it shouldn't be difficult to figure out.

https://pastebin.com/duN3ftme

**Comment by pauljoda** [comment]
The log provided doesn't tell us much, can you provide a little more info like what items shift clicking, on server or single player, I thought I disabled shift click functionality but could be wrong, I'll look at it soon but if you can provide that info in the meantime that would be very helpful, just a normal usecase that you can get the fail using vanilla items as an example
