### ISSUE TITLE
Strange recipes in Grinder

### ISSUE THREAD

**Issue by mcenderdragon** [TeamBR-Modding/AssistedProgression#28]
The grinder has alot of stupid & cheety recipes. For example any forge:gem can be made to futurepack:bitripentium (a very expensive lategame material). And any beacon_payment (a iron ingot) can be made to a gold ingot. I currently dont know why these recipes are added. But is there a way to remove them? The destroy balancing.

**Comment by pauljoda** [comment]
Once you've generated the recipes, in the config folder you can disable automatic recipes and then edit the recipes in the config in the same location
