### ISSUE TITLE
Suggestion: Ender Bull

### ISSUE THREAD

**Issue by jburrows82** [TeamBR-Modding/AssistedProgression#4]
I checked out the Trello page -- and here's a slightly comical and offbeat way to generate Ender pearls. Paul, do you remember during the The Modding Trials you made the comment next time you guys should just make a Bounce House, it would of been easier and more fun? I think my mechanical bull idea below is something that you could go animation buck wild with (pun intended) and it would be a fun thing to experience in game. I also haven't seen you make a mob yet, so the mob version idea is just there for inspiration. 
 
-------
Ender Bull (Block version)

A stationary statue that summons Endermen that "attracts them" and forces them to ride it. It acts like a Mechanical Bull spinning around (maybe tilting/bucking is feasible from the animation wizard Paul?)uncontrollably weaking them per second. It has a configurable chance rate to fully damage them to death (0.01 - 1.0). If the Endermen gets dismounted before dying it's stunned for a short duration making it easily killed without risk of teleporting away.

To craft an Ender Bull the player has to feed a Cow an ender pearl, then capture it using the Launcher. 

Crafting recipe:
- (2) Ender pearls (E)
- Laucher with the captured cow (L)
- Mob stand (S)
- (1) Block of redstone (R)
- (2) Diamonds (D)
- (2) Blocks of Iron (I)
`   E L E`
    `D S D`
    `I R I`

Some ideas for minor details:

- Plays the cow huffing sound when it summons Ender Men, along with the Ender particles
- Moos when the Endermen mounts the bull
- Plays the cow receiving damage sound while it's damaging the Endermen (Angry moo?)
- Model of the Ender Bull would be of a Cow, black with maybe a purple patch somewhere, purple eyes, and horns that just arch from the top towards the back sweeping back around like two voxels off the sides of the head. Super simple.

------------------
Ender Bull  (Mob version)

Mob that naturally allures Endermen because of the pure desire and sport of trying to ride an untamed bull. Ender Bulls are neutral entities, however hostile towards Endermen. They do not spawn naturally, but instead are an by-product of infusing the elements of the ender with overworld life. If a cow is fed ("bred") Ender Essence Feed, the parent cow spawns an Ender Bull. Once fully matured, the Ender Bull begins to gain an unnatural ability to allure Endermen at an alarming rate, which it does not like at all and lashes out against them whenever it encounters one. Maybe it was dittled by one at early age, who knows.

Ender Essence Feed is crafted with: 1 Ender Pearl, 1 Wheet, 1 Diamond Powder (Grinder makes Diamond powder right?)

If a player kills a fully matured Ender Bull it drops two Ender Pearls. If killed by a FakePlayer (or non-player source?), only drops one Ender Pearl.

Ender Bulls are very efficienct against Endermen, doing 15 points of damage per hit (3 hits to kill a vanilla Endermen). Ender Bulls are a bit tougher than Endermen, having 60 hit points (30 hearts). They do not teleport, nor are they agitated by water.

**Comment by pauljoda** [comment]
I am closing this issue for now, we will consider the ideas listed and readd them to the development board as needed
