### ISSUE TITLE
Suggestion: Ender Dragon Killer

### ISSUE THREAD

**Issue by jburrows82** [TeamBR-Modding/AssistedProgression#5]
From my understanding there aren't a lot of options for automating killing the Ender Dragon. It's one of those wonky special handling coded aspects of MC which requires hackery in my understanding. Infact I think Draconic Evolution removed their ability to kill the dragon with their Grinder in 1.10.2. But, if its feasible I propose adding something that will make it easier to automate.

------------
Ender Dragon Killer

This block accepts melee (swords) and ranged (bows) weapons. It also has a single inventory slot for ammo, for ranged weapons. Melee weapons have a reduced range of attack (16 blocks). Ranged weapons require ammo (arrows, tinkers' bolts), but have an extended range of attack (64 blocks). Weapons lose normal duration, so automation of replacing/repairing weapons and ammo would still be an idea end goal as per usual modded MC. Enchants on weapons would also be applied. 

The idea behind using melee vs. range is to aid in Obelisk designs that keep the Dragon stationary (Botania, Bloodmagic, EnderIO?). Some melee weapons in various mods also do far more damage than ranged weapons.

Ranged weapons requiring ammo I think is a way balance the machine and encourage automation with restocking requirements. 

Tinkers' integration would be idea in this block (obviously).

Recipe cost.. I would say blocks of diamond, nether star, ender pearls, dragon egg (requiring killing the dragon at least once the old fashion way). I don't think this block should require an upkeep, like RF. But for "balancing" perhaps just keep a modest rate of attack.

**Comment by Ozzymud** [comment]
As a note on this, the Woot mod has the ability to pseudo farm the dragon (doesn't actually spawn dragons. And for those who want to spawn him and contain it, there is the mod Ender Totem. Both are available in 1.12.2

**Comment by jburrows82** [comment]
Woot & Ender Totem are good alternatives, indeed. At the time of this idea, I believe Woot didn’t support dragon drops in 1.10, nor did Ender Totem exist. A lot has changed in the modded community.
