### ISSUE TITLE
Suggestion: Crucible

### ISSUE THREAD

**Issue by jburrows82** [TeamBR-Modding/AssistedProgression#6]
Crucible

For making lava, you know. The idea is it's your standard Crucible that you'd find in Skyblocks and it melts stones down into lava at a variable rate depending on the heat source supplied below it. By stone I mean it accepts granite, diorite, andesite, and not just (cobble)stone. A great way to get rid of those *ites, amiiright?

A torch (1x), lit furnace (2x), fire(3x), and lava(4x source block, 3x flowing) are acceptable heat sources beneath the Crucible. I think in Skyblock Crucibles generate 5mb per second, so 200 seconds for a bucket of lava. Using a lava source it becomes 48(?) seconds per bucket.

Crucibles would make lava power generation easier early game, but not too easily accessible.... Could always tweak the milibucket generation rate to be lower.

For crafting you wouldn't use the Skyblock clay -> porcelin route. Instead I think using a Cauldron (7 iron) and 8 bricks surrounding it ("insulation" right?) would be a fairly balanced resource cost. You can snag a cauldron from a village usually. Kinda gives the Cauldron more purpose IMO.

**Comment by majijn** [comment]
some crucibles are made out of aluminium oxide , perhaps mixing alumina and clay? 

iron crucibles would expand and break.

**Comment by pauljoda** [comment]
I am closing this issue for now, we will consider the ideas listed and readd them to the development board as needed
