### ISSUE TITLE
Suggestion: Fizzler

### ISSUE THREAD

**Issue by jburrows82** [TeamBR-Modding/AssistedProgression#7]
Fizzler

Neotech's Jetpack & Elytra chest upgrades together hands down is super fun. The Fizzler, however isn't very techy. It operates off of Flatulence. The idea of the Fizzler is when the player eats Rotten Flesh, they develop aerophagia, which generates Nitrogen, which can be ignited for propulsion. The Fizzler gains and stores propellent charge from the player eating Rotten Flesh. Players then use The Fizzler to propel themselves upwards like a Jetpack, or to slow their decent just like the Jetpack upgrade in Neotech.

Combined with an Elytra or something that mimics an Elytra would make The Fizzler perfect while progressing towards something that enables Creative flight. 

Crafting recipe... torch, (any) pants, 2 bottles, button?

**Comment by pauljoda** [comment]
I am closing this issue for now, we will consider the ideas listed and readd them to the development board as needed
