### ISSUE TITLE
Crash on start up 1.10.2

### ISSUE THREAD

**Issue by awkwaRdcaRRot** [TeamBR-Modding/AssistedProgression#9]
http://pastebin.com/fHrbzQZH

**Comment by Dyonovan** [comment]
You need to use version 4 of BookshelfAPI.

pauljoda just rewrote bookshelf and Neotech, We haven't updated AP to use the new bookshelf yet.

**Comment by awkwaRdcaRRot** [comment]
Ah I see. You night want to mention that on the mod page, I installed it on curse and just assumed it would install all proper libraries.
